name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: tharunreddy387/wisecow:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Print Kubernetes Secrets
      run: |
        echo "KUBE_SERVER: ${{ http://13.126.159.53:8001  }}"
        echo "KUBE_TOKEN: ${{ eW91ci10b2tlbi12YWx1ZQ== }}"

    - name: Deploy to Kubernetes
      uses: appleboy/kube-deploy@v2
      with:
        k8s-server: ${{ secrets.KUBE_SERVER }}
        k8s-token: ${{ secrets.KUBE_TOKEN }}
        k8s-namespace: default
        k8s-deploy: true
        k8s-deploy-type: rollout
        manifests: k8s/*.yaml
